<?php

 $TOC = array (
  0 => 
  array (
    0 => 'gshell.apm.php',
    1 => 'apm',
  ),
  1 => 
  array (
    0 => 'gshell.cp.php',
    1 => 'cp',
  ),
  2 => 
  array (
    0 => 'gshell.dockbar.php',
    1 => 'dockbar',
  ),
  3 => 
  array (
    0 => 'gshell.echo.php',
    1 => 'echo',
  ),
  4 => 
  array (
    0 => 'gshell.exit.php',
    1 => 'exit',
  ),
  5 => 
  array (
    0 => 'gshell.export.php',
    1 => 'export',
  ),
  6 => 
  array (
    0 => 'gshell.gpkg.php',
    1 => 'gpkg',
  ),
  7 => 
  array (
    0 => 'gshell.groupadd.php',
    1 => 'groupadd',
  ),
  8 => 
  array (
    0 => 'gshell.groupdel.php',
    1 => 'groupdel',
  ),
  9 => 
  array (
    0 => 'gshell.groupmod.php',
    1 => 'groupmod',
  ),
  10 => 
  array (
    0 => 'gshell.groups.php',
    1 => 'groups',
  ),
  11 => 
  array (
    0 => 'gshell.login.php',
    1 => 'login',
  ),
  12 => 
  array (
    0 => 'gshell.ls.php',
    1 => 'ls',
  ),
  13 => 
  array (
    0 => 'gshell.mainmenu.php',
    1 => 'mainmenu',
  ),
  14 => 
  array (
    0 => 'gshell.man.php',
    1 => 'man',
  ),
  15 => 
  array (
    0 => 'gshell.mkdir.php',
    1 => 'mkdir',
  ),
  16 => 
  array (
    0 => 'gshell.mv.php',
    1 => 'mv',
  ),
  17 => 
  array (
    0 => 'gshell.passwd.php',
    1 => 'passwd',
  ),
  18 => 
  array (
    0 => 'gshell.printenv.php',
    1 => 'printenv',
  ),
  19 => 
  array (
    0 => 'gshell.rm.php',
    1 => 'rm',
  ),
  20 => 
  array (
    0 => 'gshell.sudo.php',
    1 => 'sudo',
  ),
  21 => 
  array (
    0 => 'gshell.system.php',
    1 => 'system',
  ),
  22 => 
  array (
    0 => 'gshell.time.php',
    1 => 'time',
  ),
  23 => 
  array (
    0 => 'gshell.unzip.php',
    1 => 'unzip',
  ),
  24 => 
  array (
    0 => 'gshell.useradd.php',
    1 => 'useradd',
  ),
  25 => 
  array (
    0 => 'gshell.userdel.php',
    1 => 'userdel',
  ),
  26 => 
  array (
    0 => 'gshell.usermod.php',
    1 => 'usermod',
  ),
  27 => 
  array (
    0 => 'gshell.users.php',
    1 => 'users',
  ),
  28 => 
  array (
    0 => 'gshell.whoami.php',
    1 => 'whoami',
  ),
  29 => 
  array (
    0 => 'gshell.zip.php',
    1 => 'zip',
  ),
);
 $PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'Gnujiko 10.1 - User Guide',
  ),
);

