<?php

 $TOC = array (
  0 => 
  array (
    0 => 'package.gnujiko-accounts.php',
    1 => 'gnujiko-accounts',
  ),
  1 => 
  array (
    0 => 'package.database-lib.php',
    1 => 'database-lib',
  ),
  2 => 
  array (
    0 => 'package.xml-lib.php',
    1 => 'xml-lib',
  ),
  3 => 
  array (
    0 => 'package.zip-lib.php',
    1 => 'zip-lib',
  ),
  4 => 
  array (
    0 => 'package.gpkg.php',
    1 => 'gpkg',
  ),
  5 => 
  array (
    0 => 'package.apm.php',
    1 => 'apm',
  ),
  6 => 
  array (
    0 => 'package.gnujiko-base.php',
    1 => 'gnujiko-base',
  ),
  7 => 
  array (
    0 => 'package.gterminal.php',
    1 => 'gterminal',
  ),
);
 $PARENTS = array (
  0 => 
  array (
    0 => 'index.php',
    1 => 'Gnujiko 10.1 - User Guide',
  ),
);

